# Generated by Django 4.1.7 on 2023-02-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(max_length=255)),
                ('schema_data', models.JSONField()),
            ],
            options={
                'db_table': 'schema',
            },
        ),
    ]
