# Generated by Django 4.1.7 on 2023-02-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddSchema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='schema_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
