# Generated by Django 4.1.7 on 2023-03-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddSchema', '0002_alter_schema_schema_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
