# Generated by Django 4.1.7 on 2023-03-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddSchema', '0003_alter_schema_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='description',
            field=models.TextField(default='no description'),
        ),
    ]
