# Generated by Django 4.1.7 on 2023-03-23 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AddSchema', '0004_schema_description'),
        ('addDatabase', '0002_alter_database_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AddSchema.schema'),
        ),
    ]
