# Generated by Django 4.1.7 on 2023-03-23 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addDatabase', '0003_alter_database_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='schema',
            field=models.CharField(max_length=50),
        ),
    ]
