# Generated by Django 4.1.7 on 2023-03-13 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AddSchema', '0003_alter_schema_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traitement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('tables', models.JSONField()),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AddSchema.schema')),
            ],
            options={
                'db_table': 'Traitement',
            },
        ),
    ]
