# Generated by Django 4.1.7 on 2023-03-28 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraitementTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('advanced', models.BooleanField(default=False)),
                ('table_name', models.CharField(max_length=255, unique=True)),
                ('Columns', models.JSONField()),
                ('Filter', models.JSONField()),
                ('AdvancedQuery', models.CharField(max_length=255)),
                ('traitement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dab.traitement')),
            ],
            options={
                'db_table': 'TraitementTable',
            },
        ),
    ]
