# Generated by Django 4.1.7 on 2023-04-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dab', '0004_alter_traitementtable_advancedquery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traitementtable',
            name='Filter',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
