# Generated by Django 4.1.7 on 2023-04-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dab', '0005_alter_traitementtable_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traitementtable',
            name='table_name',
            field=models.CharField(max_length=255),
        ),
    ]
